"""
4-alternative multiple-choice trivia, played until the player loses. A mode is a *topic*
(games/trivium/modes.py), not a fixed mechanic - each round is generated by a random question type
from that mode's bank (games/trivium/questions/), and a correct guess chains into a new round the
same shape as MoreOrLess/Timeline; a wrong guess - or letting the timer run out - ends the game.
Deliberately a single generic Game/Round pair rather than one subclass per mode: every round has
exactly the same shape (subject + params + 4 alternatives + which is correct + what media to
show), and only *how* a round is generated varies between question types, not the game loop or
the scoring itself.

Scoring is linear by elapsed time, computed entirely in games/trivium/round.py's
TriviumRound.calculate_score - this module only owns the loop: which round comes next, when the
game is over, and the "don't repeat a subject" exclusion (falling back to allowing a repeat once
the pool of eligible subjects runs out, so the game stays infinite even against a small library -
see _build_round).
"""

from collections.abc import Mapping
from uuid import UUID, uuid4

from games.base import BaseGame
from games.trivium.modes import any_question_available, pick_question
from games.trivium.questions.base import QuestionType
from games.trivium.round import ANSWER_TIME_SECONDS, TriviumRound
from services.immich import ContentQueries

GAME_TYPE = "trivium"

MAX_ROUNDS = 0  # 0 = no limit - optional cap so a very good run doesn't run forever (mirrors Timeline's MAX_CARDS)


class TriviumGame(BaseGame):
    def __init__(
        self,
        id: UUID,
        mode: str,
        rounds: list[TriviumRound],
        immich_service: ContentQueries,
        question_types: list[QuestionType],
        score: int = 0,
        finished: bool = False,
        settings: Mapping[str, float] | None = None,
    ) -> None:
        super().__init__(
            id=id,
            game_type=GAME_TYPE,
            mode=mode,
            rounds=rounds,
            score=score,
            finished=finished,
            settings=settings,
        )
        self._immich_service = immich_service
        self._question_types = question_types

    @property
    def _max_rounds(self) -> int:
        return int(self._settings.get("max_rounds", MAX_ROUNDS))

    @property
    def answer_time_seconds(self) -> int:
        return int(self._settings.get("answer_time_seconds", ANSWER_TIME_SECONDS))

    @property
    def _used_subject_ids(self) -> frozenset[UUID]:
        """Every subject shown so far this game - a person/asset doesn't repeat as a subject
        within the same game *as long as the library has enough of them*; once that pool is
        exhausted, _build_round falls back to ignoring this so the game stays infinite instead of
        ending early against a small library (confirmed by the owner: it should be able to
        repeat)."""
        return frozenset(r.subject_id for r in self.rounds)

    @classmethod
    def start(
        cls,
        id: UUID,
        mode: str,
        immich_service: ContentQueries,
        question_types: list[QuestionType],
        settings: Mapping[str, float] | None = None,
    ) -> "TriviumGame":
        game = cls(
            id=id,
            mode=mode,
            rounds=[],
            immich_service=immich_service,
            question_types=question_types,
            settings=settings,
        )
        first_round = game._build_round(round_index=1, exclude_subject_ids=frozenset())
        if first_round is None:
            raise ValueError("not enough content in Immich to start a Trivium game")
        game.rounds.append(first_round)
        return game

    def _build_round(self, round_index: int, exclude_subject_ids: frozenset[UUID]) -> TriviumRound | None:
        question = pick_question(self._question_types, self._immich_service, exclude_subject_ids)
        if question is None and exclude_subject_ids:
            # The subject-exclusion pool is exhausted (a library with fewer eligible subjects than
            # rounds already played) - allow a repeat rather than ending the game, so it stays
            # infinite the same way MoreOrLess/Timeline fall back to repeats once their own
            # recent-exclude window covers the whole pool.
            question = pick_question(self._question_types, self._immich_service, frozenset())
        if question is None:
            return None
        return TriviumRound.of(id=uuid4(), game_id=self.id, round_index=round_index, question=question)

    def _any_question_available(self, exclude_subject_ids: frozenset[UUID]) -> bool:
        if any_question_available(self._question_types, self._immich_service, exclude_subject_ids):
            return True
        # Same exhausted-pool fallback as _build_round.
        return bool(exclude_subject_ids) and any_question_available(
            self._question_types, self._immich_service, frozenset()
        )

    def has_next_round(self) -> bool:
        current = self.current_round
        if not current.correct:
            return False
        max_rounds = self._max_rounds
        if max_rounds and current.round_index >= max_rounds:
            return False
        return self._any_question_available(self._used_subject_ids)

    def create_next_round(self) -> TriviumRound:
        next_round = self._build_round(self.current_round.round_index + 1, self._used_subject_ids)
        if next_round is None:
            raise ValueError("no more eligible content - has_next_round() should have returned False")
        return next_round
