"""Plumbing shared across question types *within* Trivium (the birthday_year/birthday_day_month/
birthday_full_date trio, plus photos_first_asset_year's own year distractors) - not shared with any
other game, same "duplication beats coupling" boundary games/base.py's docstring draws elsewhere,
just drawn one level narrower here since these all belong to the same game. See
games/trivium/questions/base.py's QuestionType for the contract every type still implements on its
own - nothing here decides *whether* a type can generate, only helps once it's decided to.

Noise magnitude is deliberately graduated by how specific the question is (confirmed by the
owner): birthday_year (year only) varies the widest, since that's the only field it has to work
with; birthday_day_month (day+month, no year) needs both of those fields to actually move, not
just the day; birthday_full_date (day+month+year) is the most specific, so its year noise is kept
the tightest (+/-1) even though its day/month still range as widely as birthday_day_month's."""

import random
from collections.abc import Callable, Hashable
from datetime import date, timedelta

# "All" named+birthdated/photographed people, for a library's real min/max year (birth year or
# first-photo year) - a family-sized library (this app's whole reason to exist, see CLAUDE.md)
# never comes close to this, so one unbounded-in-practice query is simpler than a dedicated
# MIN/MAX query for data get_persons already returns.
LIBRARY_SAMPLE_LIMIT = 10_000


def pick_distractor_years(correct_year: int, min_year: int, max_year: int) -> list[int]:
    """3 distinct years, none equal to `correct_year`, clamped to [min_year, max_year] - the
    library's own plausible range, never a year it couldn't actually contain."""
    taken = {correct_year}
    distractors: list[int] = []
    window = 2
    span = max_year - min_year
    while len(distractors) < 3:
        offsets = [o for o in range(-window, window + 1) if o != 0]
        year = max(min_year, min(max_year, correct_year + random.choice(offsets)))
        if year not in taken:
            taken.add(year)
            distractors.append(year)
        elif window < span:
            window += 1
    return distractors


def _pick_one_distractor(
    correct: date,
    taken: set[Hashable],
    *,
    base_window: int,
    max_window: int,
    key: Callable[[date], Hashable],
    valid: Callable[[date], bool],
) -> date:
    """One distractor at least `base_window` days from `correct`, widening (on a collision or an
    invalid candidate) up to `max_window` if needed. `key` maps a date to whatever must be unique
    (the date itself, or just its (month, day)) - mutates `taken` with the winning key so a
    caller drawing several of these in a row never repeats one. `valid` rejects a candidate
    outright (a disallowed year, a disallowed 29 February)."""
    window = base_window
    while True:
        offsets = [o for o in range(-window, window + 1) if o != 0]
        candidate = correct + timedelta(days=random.choice(offsets))
        candidate_key = key(candidate)
        if valid(candidate) and candidate_key not in taken:
            taken.add(candidate_key)
            return candidate
        window = min(window + base_window, max_window)


def _not_29_february_unless_real(correct: date) -> Callable[[date], bool]:
    real_is_29_february = (correct.month, correct.day) == (2, 29)
    return lambda d: real_is_29_february or (d.month, d.day) != (2, 29)


def _day_month_key(d: date) -> Hashable:
    return (d.month, d.day)


def pick_day_month_distractors(correct: date) -> list[date]:
    """3 dates whose (month, day) is distinct from `correct`'s and from each other, generated by
    real date + timedelta noise (never field-level day/month arithmetic, which could produce
    "day 32" or "30 de febrero") - no year-range clamp: every day-of-year is an equally plausible
    birthday, there's no "implausible" one. Each of the 3 is drawn from a progressively wider
    window (30/90/180 days) rather than all from the same one, so month (not just day) reliably
    varies too instead of the search settling for 3 close-together dates that all happen to be
    distinct. Never introduces 29 February as a distractor unless that's genuinely the answer."""
    taken: set[Hashable] = {_day_month_key(correct)}
    valid = _not_29_february_unless_real(correct)
    return [
        _pick_one_distractor(correct, taken, base_window=w, max_window=180, key=_day_month_key, valid=valid)
        for w in (30, 90, 180)
    ]


def pick_full_date_distractors(correct: date) -> list[date]:
    """3 distinct full dates, none equal to `correct`, generated by real date + timedelta noise -
    day/month vary as widely as pick_day_month_distractors' (30/90/300-day tiers), but the *year*
    is kept within +/-1 of the real one: a full date is the most specific question type, so its
    year noise stays the tightest of the three birthday_* types rather than reusing
    birthday_year's wider spread. Month/day arithmetic is never done independently of a real date,
    so a rejected candidate is always "outside the plausible year", never an invalid calendar
    date. Never introduces 29 February as a distractor unless that's genuinely the answer."""
    min_year, max_year = correct.year - 1, correct.year + 1
    not_29_february = _not_29_february_unless_real(correct)

    def valid(d: date) -> bool:
        return min_year <= d.year <= max_year and not_29_february(d)

    taken: set[Hashable] = {correct}
    return [
        _pick_one_distractor(correct, taken, base_window=w, max_window=1000, key=lambda d: d, valid=valid)
        for w in (30, 90, 300)
    ]
