"""Plumbing shared across question types *within* Trivium (the birthday_year/birthday_day_month/
birthday_full_date trio, plus photos_first_asset_year's own year distractors) - not shared with any
other game, same "duplication beats coupling" boundary games/base.py's docstring draws elsewhere,
just drawn one level narrower here since these all belong to the same game. See
games/trivium/questions/base.py's QuestionType for the contract every type still implements on its
own - nothing here decides *whether* a type can generate, only helps once it's decided to.

Noise magnitude is deliberately graduated by how specific the question is (confirmed by the
owner): birthday_year (year only) varies the widest, since that's the only field it has to work
with; birthday_day_month (day+month, no year) needs both of those fields to actually move, not
just the day; birthday_full_date (day+month+year) is the most specific, so its year noise stays
within +/-1 of the real one - but that bound is deliberately spread across the 3 distractors via
an explicit weighted pattern (_pick_year_offsets below) rather than left to fall out of the
day/month noise search, specifically so the year alone is never a reliable tell: sometimes every
distractor keeps the real year, sometimes one or two of them differ by a year, and sometimes all
three do - that last pattern makes the *real* answer's year the one that stands out, which the old
search-driven approach could never produce (confirmed by the owner as the actual gap being
closed)."""

import random
from collections.abc import Callable, Hashable
from datetime import date, timedelta

# "All" named+birthdated/photographed people, for a library's real min/max year (birth year or
# first-photo year) - a family-sized library (this app's whole reason to exist, see CLAUDE.md)
# never comes close to this, so one unbounded-in-practice query is simpler than a dedicated
# MIN/MAX query for data get_persons already returns.
LIBRARY_SAMPLE_LIMIT = 10_000


def pick_distractor_years(correct_year: int, min_year: int, max_year: int) -> list[int]:
    """3 distinct years, none equal to `correct_year`, clamped to [min_year, max_year] - the
    library's own plausible range, never a year it couldn't actually contain."""
    taken = {correct_year}
    distractors: list[int] = []
    window = 2
    span = max_year - min_year
    while len(distractors) < 3:
        offsets = [o for o in range(-window, window + 1) if o != 0]
        year = max(min_year, min(max_year, correct_year + random.choice(offsets)))
        if year not in taken:
            taken.add(year)
            distractors.append(year)
        elif window < span:
            window += 1
    return distractors


def _pick_one_distractor(
    correct: date,
    taken: set[Hashable],
    *,
    base_window: int,
    max_window: int,
    key: Callable[[date], Hashable],
    valid: Callable[[date], bool],
    adjust: Callable[[date], date] = lambda d: d,
) -> date:
    """One distractor at least `base_window` days from `correct`, widening (on a collision or an
    invalid candidate) up to `max_window` if needed. `key` maps a date to whatever must be unique
    (the date itself, or just its (month, day)) - mutates `taken` with the winning key so a
    caller drawing several of these in a row never repeats one. `valid` rejects a candidate
    outright (a disallowed 29 February). `adjust` post-processes the raw day/month-noised
    candidate before it's checked against `valid`/`key` - identity by default
    (pick_day_month_distractors/pick_distractor_years don't need it), but
    pick_full_date_distractors uses it to force a specific year onto the noised day/month (see
    below) - a ValueError from `adjust` itself (forcing 29 February onto a non-leap year) counts
    as an invalid candidate too, same as `valid` returning False."""
    window = base_window
    while True:
        offsets = [o for o in range(-window, window + 1) if o != 0]
        raw_candidate = correct + timedelta(days=random.choice(offsets))
        try:
            candidate = adjust(raw_candidate)
        except ValueError:
            window = min(window + base_window, max_window)
            continue
        candidate_key = key(candidate)
        if valid(candidate) and candidate_key not in taken:
            taken.add(candidate_key)
            return candidate
        window = min(window + base_window, max_window)


def _not_29_february_unless_real(correct: date) -> Callable[[date], bool]:
    real_is_29_february = (correct.month, correct.day) == (2, 29)
    return lambda d: real_is_29_february or (d.month, d.day) != (2, 29)


def _day_month_key(d: date) -> Hashable:
    return (d.month, d.day)


def pick_day_month_distractors(correct: date) -> list[date]:
    """3 dates whose (month, day) is distinct from `correct`'s and from each other, generated by
    real date + timedelta noise (never field-level day/month arithmetic, which could produce
    "day 32" or "30 de febrero") - no year-range clamp: every day-of-year is an equally plausible
    birthday, there's no "implausible" one. Each of the 3 is drawn from a progressively wider
    window (30/90/180 days) rather than all from the same one, so month (not just day) reliably
    varies too instead of the search settling for 3 close-together dates that all happen to be
    distinct. Never introduces 29 February as a distractor unless that's genuinely the answer."""
    taken: set[Hashable] = {_day_month_key(correct)}
    valid = _not_29_february_unless_real(correct)
    return [
        _pick_one_distractor(correct, taken, base_window=w, max_window=180, key=_day_month_key, valid=valid)
        for w in (30, 90, 180)
    ]


def _pick_year_offsets() -> list[int]:
    """One year offset (-1, 0, or +1, relative to the real year) per distractor - 4 equally-weighted
    patterns, confirmed by the owner: every distractor keeps the real year (no signal at all);
    exactly one differs; one keeps it while the other two split +1/-1; or all three differ. That
    last pattern is the one the old year-clamped search could never produce - with every
    distractor off-year, the *real* answer's year becomes the single one that stands out, instead
    of the year always being a free tell against whichever distractor happened to drift."""
    pattern = random.choice(("none_off", "one_off", "two_off", "all_off"))
    if pattern == "none_off":
        offsets = [0, 0, 0]
    elif pattern == "one_off":
        offsets = [0, 0, random.choice((-1, 1))]
    elif pattern == "two_off":
        offsets = [0, 1, -1]
    else:
        offsets = [random.choice((-1, 1)) for _ in range(3)]
    random.shuffle(offsets)
    return offsets


def pick_full_date_distractors(correct: date) -> list[date]:
    """3 distinct full dates, none equal to `correct`. Day/month noise is generated exactly like
    pick_day_month_distractors' (real date + timedelta, same 30/90/300-day tiers as before this
    picker's year handling changed), then each candidate's year is *forced* to whatever
    _pick_year_offsets assigned that distractor (never left to fall out of the day/month
    timedelta itself, which drifts unpredictably once the noise window crosses a year boundary).
    Forcing the year can turn a valid day/month into an invalid calendar date (29 February onto a
    non-leap target year) - `_pick_one_distractor`'s `adjust` hook surfaces that as a ValueError,
    which is treated as an invalid candidate the same as the explicit `valid` check below. Never
    introduces 29 February as a distractor unless that's genuinely the answer."""
    year_offsets = _pick_year_offsets()
    not_29_february = _not_29_february_unless_real(correct)

    taken: set[Hashable] = {correct}
    distractors = []
    for base_window, offset in zip((30, 90, 300), year_offsets, strict=True):
        target_year = correct.year + offset

        def force_year(d: date, target_year: int = target_year) -> date:
            return d.replace(year=target_year)

        distractors.append(
            _pick_one_distractor(
                correct,
                taken,
                base_window=base_window,
                max_window=1000,
                key=lambda d: d,
                valid=not_29_february,
                adjust=force_year,
            )
        )
    return distractors
