"""birthday_year question type - "what year was {person} born", with the 3 wrong alternatives
generated by noise on the real year rather than other people's real birth years: none of the
distractors correspond to an actual person, so a familiar face can't be used to eliminate one by
"that's not when so-and-so was born"."""

import random
from uuid import UUID

from games.trivium.questions._shared import LIBRARY_SAMPLE_LIMIT, pick_distractor_years
from games.trivium.questions.base import GeneratedQuestion, MediaSpec
from services.immich import ContentQueries

KIND = "birthday_year"


def _birth_years(immich_service: ContentQueries) -> list[int]:
    # with_birthdate=True already filters out anyone with no birth_date, so it's never None here.
    persons = immich_service.get_persons(named_only=True, with_birthdate=True, limit=LIBRARY_SAMPLE_LIMIT)
    return [p.birth_date.year for p in persons]


class BirthYearQuestion:
    def can_generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> bool:
        if not immich_service.get_persons(
            named_only=True, with_birthdate=True, limit=1, exclude_ids=exclude_subject_ids
        ):
            return False
        years = _birth_years(immich_service)
        # A closed range of >= 4 distinct integer years always has >= 3 other than whichever one
        # is correct - exactly what pick_distractor_years needs to terminate.
        return bool(years) and max(years) - min(years) >= 3

    def generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> GeneratedQuestion:
        [subject] = immich_service.get_persons(
            named_only=True, with_birthdate=True, randomize=True, limit=1, exclude_ids=exclude_subject_ids
        )
        # with_birthdate=True already filters out anyone with no birth_date, so it's never None here.
        correct_year = subject.birth_date.year

        years = _birth_years(immich_service)
        distractor_years = pick_distractor_years(correct_year, min(years), max(years))

        alternatives: list[int] = [*distractor_years, correct_year]
        random.shuffle(alternatives)

        return GeneratedQuestion(
            question_kind=KIND,
            subject_id=subject.id,
            params={"person_id": str(subject.id), "person_name": subject.name},
            alternatives=alternatives,
            correct_index=alternatives.index(correct_year),
            # Confirmed by the owner: show the subject's face here too, not just the name.
            media=MediaSpec(kind="person_thumbnail", person_id=subject.id),
        )
