"""birthday_year question type (TRIVIUM.md §2.1 #1) - "what year was {person} born", with the 3
wrong alternatives generated by noise on the real year rather than other people's real birth
years (§2.6): none of the distractors correspond to an actual person, so a familiar face can't be
used to eliminate one by "that's not when so-and-so was born"."""

import random
from uuid import UUID

from games.trivium.questions.base import NONE_MEDIA, GeneratedQuestion
from services.immich import ContentQueries

KIND = "birthday_year"

# Base noise window in years either side of the real one (TRIVIUM.md §2.6/§7 flags the exact
# magnitude as still to be tuned by playing, not decided a priori) - widened by one whenever a
# sampled year collides with one already picked, capped at the library's own birth-year span
# (§2.6 rule 2: never suggest a year the library couldn't plausibly contain).
_BASE_NOISE_YEARS = 2
# "All" named+birthdated people, for the library's min/max birth year - a family-sized library
# (this app's whole reason to exist, see CLAUDE.md) never comes close to this, so one unbounded-in-
# practice query is simpler than a dedicated MIN/MAX query for the same data get_persons already
# returns.
_LIBRARY_SAMPLE_LIMIT = 10_000


def _birth_years(immich_service: ContentQueries) -> list[int]:
    # with_birthdate=True already filters out anyone with no birth_date, so it's never None here.
    persons = immich_service.get_persons(named_only=True, with_birthdate=True, limit=_LIBRARY_SAMPLE_LIMIT)
    return [p.birth_date.year for p in persons]


def _pick_distractor_years(correct_year: int, min_year: int, max_year: int) -> list[int]:
    """3 distinct years, none equal to `correct_year`, clamped to [min_year, max_year] - see
    TRIVIUM.md §2.6 rules 1-3 (date arithmetic isn't needed at year granularity - a plain int
    offset can't produce an invalid year the way day/month arithmetic could)."""
    taken = {correct_year}
    distractors: list[int] = []
    window = _BASE_NOISE_YEARS
    span = max_year - min_year
    while len(distractors) < 3:
        offsets = [o for o in range(-window, window + 1) if o != 0]
        year = max(min_year, min(max_year, correct_year + random.choice(offsets)))
        if year not in taken:
            taken.add(year)
            distractors.append(year)
        elif window < span:
            window += 1
    return distractors


class BirthYearQuestion:
    def can_generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> bool:
        if not immich_service.get_persons(
            named_only=True, with_birthdate=True, limit=1, exclude_ids=exclude_subject_ids
        ):
            return False
        years = _birth_years(immich_service)
        # A closed range of >= 4 distinct integer years always has >= 3 other than whichever one
        # is correct - exactly what _pick_distractor_years needs to terminate.
        return bool(years) and max(years) - min(years) >= 3

    def generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> GeneratedQuestion:
        [subject] = immich_service.get_persons(
            named_only=True, with_birthdate=True, randomize=True, limit=1, exclude_ids=exclude_subject_ids
        )
        # with_birthdate=True already filters out anyone with no birth_date, so it's never None here.
        correct_year = subject.birth_date.year

        years = _birth_years(immich_service)
        distractor_years = _pick_distractor_years(correct_year, min(years), max(years))

        alternatives: list[int] = [*distractor_years, correct_year]
        random.shuffle(alternatives)

        return GeneratedQuestion(
            question_kind=KIND,
            subject_id=subject.id,
            params={"person_id": str(subject.id), "person_name": subject.name},
            alternatives=alternatives,
            correct_index=alternatives.index(correct_year),
            media=NONE_MEDIA,
        )
