"""photos_first_asset_year question type - "what year is {person}'s first photo from", with the
answer being only the year (confirmed by the owner: the exact date of someone's first tagged photo
is unguessable, and distractors for it would be indistinguishable) - distractors generated by noise
on the real year, clamped to the range of first-photo years the library actually covers."""

import random
from uuid import UUID

from games.trivium.questions._shared import LIBRARY_SAMPLE_LIMIT, pick_distractor_years
from games.trivium.questions.base import GeneratedQuestion, MediaSpec
from services.immich import ContentQueries

KIND = "photos_first_asset_year"


def _first_asset_years(immich_service: ContentQueries) -> list[int]:
    # named_only already implies at least one tagged, visible asset (get_persons requires a
    # thumbnailPath), so get_person_first_asset_date is never None for any of these.
    people = immich_service.get_persons(named_only=True, limit=LIBRARY_SAMPLE_LIMIT)
    years = []
    for p in people:
        first_date = immich_service.get_person_first_asset_date(p.id)
        if first_date is not None:
            years.append(first_date.year)
    return years


class PhotosFirstAssetYearQuestion:
    def can_generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> bool:
        if not immich_service.get_persons(named_only=True, limit=1, exclude_ids=exclude_subject_ids):
            return False
        years = _first_asset_years(immich_service)
        # Same rationale as BirthYearQuestion's own check - a closed range of >= 4 distinct years
        # always leaves >= 3 valid distractor years besides the correct one.
        return bool(years) and max(years) - min(years) >= 3

    def generate(self, immich_service: ContentQueries, exclude_subject_ids: frozenset[UUID]) -> GeneratedQuestion:
        [subject] = immich_service.get_persons(
            named_only=True, randomize=True, limit=1, exclude_ids=exclude_subject_ids
        )
        correct_date = immich_service.get_person_first_asset_date(subject.id)
        if correct_date is None:
            raise ValueError("subject has no first asset date - can_generate() should have returned False")
        correct_year = correct_date.year

        years = _first_asset_years(immich_service)
        distractor_years = pick_distractor_years(correct_year, min(years), max(years))

        alternatives: list[int] = [*distractor_years, correct_year]
        random.shuffle(alternatives)

        return GeneratedQuestion(
            question_kind=KIND,
            subject_id=subject.id,
            params={"person_id": str(subject.id), "person_name": subject.name},
            alternatives=alternatives,
            correct_index=alternatives.index(correct_year),
            media=MediaSpec(kind="person_thumbnail", person_id=subject.id),
        )
